import Navbar from "@/app/_components/Navbar";
import { ClerkProvider } from "@clerk/nextjs";
import { GeistSans } from "geist/font/sans";
import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Social Media - Siam",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={GeistSans.className}>
          <div className="flex flex-col h-dvh">
            <div className="w-full bg-white md:px-8 lg:px-16 xl:px-32 2xl:px-64">
              <Navbar />
            </div>
            <div className="bg-slate-100 md:px-8 flex-grow lg:px-16 xl:px-32 2xl:px-64">
              {children}
            </div>
          </div>
        </body>
      </html>
    </ClerkProvider>
  );
}
